# Specify analysis options.
#
# For a list of lints, see: https://dart.dev/tools/linter-rules
# For guidelines on configuring static analysis, see:
# https://dart.dev/tools/analysis
#
# There are other similar analysis options files in the flutter repos,
# which should be kept in sync with this file:
#
#   - analysis_options.yaml (this file)
#   - https://github.com/flutter/engine/blob/main/analysis_options.yaml
#   - https://github.com/flutter/packages/blob/main/analysis_options.yaml
#
# This file contains the analysis options used for code in the flutter/flutter
# repository.

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
    
  errors:
    close_sinks: ignore
    missing_required_param: error
    missing_return: error
    invalid_annotation_target: ignore
  exclude:
    - test/.test_coverage.dart
    - lib/generated_plugin_registrant.dart

linter:
  rules:
    - always_declare_return_types
    - always_require_non_null_named_parameters
    - annotate_overrides
    - avoid_bool_literals_in_conditional_expressions
    - constant_identifier_names
    - prefer_const_declarations
    - prefer_const_constructors
    - always_put_control_body_on_new_line
    - always_put_required_named_parameters_first
    - avoid_annotating_with_dynamic
    - avoid_escaping_inner_quotes
    - avoid_empty_else
    - avoid_final_parameters
    - avoid_function_literals_in_foreach_calls
    - use_key_in_widget_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - avoid_unused_constructor_parameters
    - sort_child_properties_last
    - prefer_typing_uninitialized_variables
    - avoid_void_async
    - avoid_redundant_argument_values
    - use_super_parameters
    - curly_braces_in_flow_control_structures
    - no_logic_in_create_state
    - avoid_null_checks_in_equality_operators
    - sort_constructors_first

    